name: Create FlameOS Kernel Patch

on:
  workflow_dispatch:
    inputs:
      base_version:
        description: "Base Linux version (e.g., 6.14.6)"
        required: true
        default: "6.14.6"

jobs:
  generate-patch:
    runs-on: ubuntu-latest
    name: Generate and Upload Patch
    steps:
      - name: Checkout modified kernel (your repo)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zstd curl tar

      - name: Download original Linux source
        run: |
          curl -LO https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ github.event.inputs.base_version }}.tar.xz
          tar -xf linux-${{ github.event.inputs.base_version }}.tar.xz

      - name: Generate patch
        run: |
          diff -Naur linux-${{ github.event.inputs.base_version }} . > linux-v${{ github.event.inputs.base_version }}-flameos.patch || true
          zstd -19 linux-v${{ github.event.inputs.base_version }}-flameos.patch -o linux-v${{ github.event.inputs.base_version }}-flameos.patch.zst

      - name: Create GitHub Release and upload patch
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.base_version }}-flameos
          name: Linux v${{ github.event.inputs.base_version }} - FlameOS Patch
          files: |
            linux-v${{ github.event.inputs.base_version }}-flameos.patch.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
